version: '3.8'

services:
  app:
    restart: always
    depends_on:
      - payment-postgres
      - payment-rabbitmq
      - payment-redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      HTTP_ADDR: ":8080"
      DSN: "postgres://user:password@payment-postgres:5432/payments?sslmode=disable"
      MIGRATIONS_PATH: "file://migrations"
      RABBITMQ_URL: "amqp://guest:guest@payment-rabbitmq:5672/"
      REDIS_URL: "payment-redis:6379"
    #      wait for services to be available before connection to them
    command: [ "./wait-for-it.sh", "payment-postgres:5432", "rabbitmq:5672", "payment-redis:6379", "--timeout=10", "--", "./app" ]

  payment-postgres:
    image: postgres:13
    container_name: payment-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payments

  payment-rabbitmq:
    container_name: payment-rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  payment-redis:
    image: redis:6.2.7-alpine
    container_name: payment-redis
    restart: always
    ports:
      - "6379:6379"
